<section id="searchNav" data-role="page">
	<header data-role="header" role="banner"><h1>Menu</h1></header>
	<div class="ui-dialog ui-content">
		<ul data-role="listview">
			<li><a href="<?=BASEURL;?>">Home</a></li>
			<li><a href="<?=BASEURL;?>profile">Company Profile</a></li>
			<li><a href="<?=BASEURL;?>profile/marketing">Marketing Profile</a></li>
			<li><a href="http://www.sixstrangetales.com">Six Strange Tales</a></li>
			<li><a href="<?=BASEURL;?>curve">the Curve</a></li>
			<li><a href="http://www.noveltysoundbytes.com/blogOsphere/wp-login.php">BlogOsphere</a></li>
			<li><a href="http://www2.netfirms.com/mail/index.bml?m=1">Webmail</a></li>
			<li><a href="https://secure.netfirms.com/secure/login.bml?err=">Netfirms</a></li>
			<li><a href="http://sakiwinki.com/pages/portfolio.html">Developer</a></li>
			<li><a href="<?=BASEURL;?>admin">Admin</a></li>
			<li><a href="<?=BASEURL;?>admin/logout">Log Out</a></li>
		</ul>
	</div>
</section>	