<section>
		<h2>Novelty Soundbytes</h2>
	  <p>Novelty Soundbytes is a brand that specializes in technology. Current technologies include building, maintaining and redesigning corporate online properties using cutting edge programming:</p>
		<ul class="group">
			<li>PHP 5</li>
			<li>Zend Frameworks</li>
			<li>MVC Code Base</li>
			<li>HTML5</li>
			<li>CSS 1-3</li>
			<li>jQuery libraries</li>
			<li>jQuery Mobile</li>
			<li>Cross Browser Compatibility and Compliance</li>
		</ul>
		<p>Recently Novelty Soundbytes has partnered with Kindle and published it's first eBook <i>Six Strange Tales</i>. It's an exciting venture and in 2012 there is much more to come.</p>
</section>