<div class="ui-dialog ui-content">
	<ul data-role="listview">
		<li>
			<form id="searchDialog" data-role="search">
				<input data-type="search" class="ui-listview-filter ui-bar-c" />
			</form>
		</li>
		<li><a href="<?=BASEURL;?>/">Home</a></li>
		<li><a href="<?=BASEURL;?>/tech/profile">Company Profile</a></li>
		<li><a href="<?=BASEURL;?>/tech/profile/marketing">Marketing Profile</a></li>
		<li><a href="<?=BASEURL;?>/tech/curve">the Curve</a></li>
		<li><a href="http://www.noveltysoundbytes.com/blogOsphere/">BlogOsphere</a></li>
		<li><a href="<?=BASEURL;?>/tech/admin">Amin</a></li>
	</ul>
</div>