<div class="ui-dialog ui-content">
	<ul data-role="listview">
		<li>
			<form id="searchDialog" data-role="search">
				<input data-type="search" class="ui-listview-filter ui-bar-c" />
			</form>
		</li>
		<li><a href="<?=Zend_Controller_Front::getInstance()->getBaseUrl();?>">Home</a></li>
		<li><a href="<?=Zend_Controller_Front::getInstance()->getBaseUrl();?>/profile">Company Profile</a></li>
		<li><a href="<?=Zend_Controller_Front::getInstance()->getBaseUrl();?>/profile/marketing">Marketing Profile</a></li>
	</ul>
</div>