<!-- application/layouts/scripts/layout.phtml -->

<?php include_once 'head.phtml'; ?>

	<body dir="ltr">
		<section id="<?=ID;?>" data-role="page" class="ui-body-d" data-url="<?=DATAURL;?>">
			
				<?php 
					include_once 'header.phtml';
					//include_once 'nav.phtml';
					echo $this->layout()->content;
					include_once 'leftRail.phtml';
					include_once 'footer.phtml';
				?>
				
		</section>
	</body>
</html>