<!-- application/layouts/scripts/layout.phtml -->

<?php 
	include_once 'head.phtml'; 
	$id = array_pop(explode("/", $_SERVER["REQUEST_URI"]));
	$dataURL = $_SERVER["REQUEST_URI"];
?>

	<body dir="ltr">
		<section id="<?=$id;?>" data-role="page" class="ui-body-d" data-url="<?=$dataURL;?>">
			
				<?php 
					include_once 'header.phtml';
					//include_once 'nav.phtml';
					echo $this->layout()->content;
					include_once 'leftRail.phtml';
					include_once 'footer.phtml';
				?>
				
		</section>
	</body>
</html>