	
		<select id="menu" name="" data-icon="arrow-d">
			<option value="<?=$this->baseUrl();?>">Home</option>
			<option value="<?=$this->baseUrl();?>/profile">Company Profile</option>
			<option value="<?=$this->baseUrl();?>/profile/marketing">Marketing Profile</option>
			<option value="<?=$this->baseUrl();?>/curve">Staying Ahead of the Curve</option>
			<option value="http://www.noveltysoundbytes.com/blogOsphere">blogOsphere</option>
			<option value="<?=$this->baseUrl();?>/login">Admin</option>
		</select>	