
<section id="css3" data-role="page" class="ui-body-d">
	<header data-role="header" role="banner">
		<h1>nSb - CSS3</h1>
		<a href="<?=BASEURL;?>index/nav" data-icon="search" data-iconpos="notext" data-rel="dialog" class="ui-btn-right">Search</a>
	</header>
	<section>
		<?php include_once 'curveNav.phtml';?>
		<img src="http://farm4.static.flickr.com/3155/2636513939_cd75b704ec.jpg" width=270 />
		<p>CSS3 - Progessive Enhancement</p>
		<p><a href="#pe">Progressive Enhancement</a></p>
	</section>
</section>
<section id="pe" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/progressiveEnhancement.phtml';?>
	<a href="#stylings">Stylings</a>
</section> 
<section id="stylings" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/stylings.phtml';?>
	<a href="#toolBoxes">Tool Boxes</a>
</section> 
<section id="toolBoxes" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/toolBoxes.phtml';?>
	<a href="#animation">Animation</a>
</section> 
<section id="animation" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/animation.phtml';?>
	<a href="#webFonts">Web Fonts</a>
</section> 
<section id="webFonts" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/webFonts.phtml';?>
	<a href="#mediaQueries">Media Queries</a>
</section> 
<section id="mediaQueries" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/mediaQueries.phtml';?>
	<a href="#browserSupport">Browser Support</a>
</section> 
<section id="browserSupport" data-role="page" class="ui-body-d"> 
	<?php include_once 'page3_css3/browserSupport.phtml';?>
	<a href="#css3">css3</a>
</section> 