<!-- main navigator - begin -->
	<ul id="main_navi">   
		<li class="active"><strong><a href="<?=BASEURL;?>curve" rel="external">the Curve</a></strong> | </li>  
		<li><strong><a href="<?=BASEURL;?>curve/html5" rel="external">HTML5</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/css3" rel="external">CSS3</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/jquery" rel="external">jQuery</a></strong></li> 
	</ul> 
<!-- main navigator - end -->	