
<section id="jQuery" data-role="page" class="ui-body-d">
	<header data-role="header" role="banner">
		<h1>nSb - jQuery</h1>
		<a href="<?=BASEURL;?>index/nav" data-icon="search" data-iconpos="notext" data-rel="dialog" class="ui-btn-right">Search</a>
	</header>
	<section>
		<?php include_once 'curveNav.phtml';?>
		<img src="http://farm4.static.flickr.com/3155/2636513939_cd75b704ec.jpg" width=270 /> 
		<p>jQuery</p> 
		<p>Staying Ahead of the Curve is built in jQuery and jQuery Mobile. Documentation has stopped due to site development. Stay tuned.</p>
	</section>
</section>