<header data-role="header" role="banner">
	<h1>nSb - Fun Video</h1>
	<a href="<?=BASEURL;?>index/nav" data-icon="search" data-iconpos="notext" data-rel="dialog" class="ui-btn-right">Search</a>
</header>
<!-- main navigator - begin -->
	<ul id="main_navi">   
		<li class="active"><strong><a href="<?=BASEURL;?>curve" rel="external">the Curve</a></strong> | </li>  
		<li><strong><a href="<?=BASEURL;?>curve/html5" rel="external">HTML5</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/css3" rel="external">CSS3</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/jquery" rel="external">jQuery</a></strong></li> 
	</ul> 
<!-- main navigator - end -->
<section id="video">
	<h1>Playing video using HTML5</h1>
	<p>The video /audio tag is used with a fallback method. The browser creates the controls and method of play pending viable format. The most used formats are mp4, ogg, webM and vorbis and ofcourse .swf via objects.</p>
	<video preload="auto" controls style="height:270px;width:270px;" poster="cdn/images/6SThtmlEmail.png">
		<source src="assets/Campusfood_FINAL.m4v" type="video/mp4">
		<source src="movie.ogg" type="video/ogg">
		<object width=270 height=270 data="movie.swf">
			<param name="movie"  value="">
			<embed src="movie.swf" width=270 height=270>
		</object>
		<p>Browser won't display</p>
	</video>
</section>