<section id="marketingProfile">
	 <h2>Marketing Profile</h2>
   <p>Recently nSb entered into an agreement with Kindle and the good people at Crackerhouse Publishing Intl. and branched off into the world of eBook publishing.</p>
   <p>The first exciting title under nSb publishing LLC. is <i>Six Strange Tales</i> by author Individual Eleven. Future titles include <i>The Religious Argument: Web Design vs Web Development</i>, <i>Cooking with Camille: Yummy Recipes</i> and <i>Molly Kills Kong</i>.</p>
   <hr size="2" />
   <p>Novelty Soundbytes originated evolving from the world of music, film and television. A few notable clients we've worked with include:</p>
   <?=$this->other; ?>
   <hr size="2" />
   <p>Other more web based affiliates include:</p>
   <?=$this->companies; // get data object from controller?>
</section>