<header data-role="header" role="banner"><h1>nSb - Animations</h1></header>
<!-- main navigator - begin -->
	<ul id="main_navi">   
		<li class="active"><strong><a href="<?=BASEURL;?>curve">the Curve</a></strong> | </li>  
		<li><strong><a href="<?=BASEURL;?>curve/html5">HTML5</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/css3">CSS3</a></strong> | </li>
		<li><strong><a href="<?=BASEURL;?>curve/jQuery">jQuery</a></strong></li> 
	</ul> 
<!-- main navigator - end -->
	<section id="animations">
 		<h3>Double Background-Image</h3>
 		<p>Another cool feature is the double background image feature. In essence you could have 2 different background images exist on one tag using:<br />
 		background-image:url(foo.jpg),url(bar.jpg); reasonably combined with repeat-x, repeat-x, background-position etc;</p>
 		<h3>Background-Clipping</h3>
 		<div class="clip">
	 		<p>Using this feature you can clip a background to a border box, padding-box or content box, however not the margin-box using browser specificity:<br /> -webkit-background-clip:padding-box;</p>
			<p>In safari and iPhone a helpful complementary feature to this is -webkit-background-origin: padding-box;</p>
			<p>This feature is widely supported however only in modern browsers.</p>
		</div>
		
		<h3>Rotate / Translate / Skew</h3>
		<p>Make the box below rotate (hover over). Pretty cool hunh. Now slide. Now skew. Starting to get the feeling we can do anything. Notice the text is still editable. Only in modern browsers.</p>
		
		<div class="rotate">Rotate</div>
		<div class="translate">Translate</div>
		<div class="skew">Skew</div>
		<div class="rotate_3D">Rotate 3D</div>
		<div class="rotate_right">Rotate 3D</div>
	</section>